language: python
python:
  - "2.7"
env:
  #- DJANGO=https://github.com/django/django/archive/master.tar.gz
  #- DJANGO_PACKAGE="Django>=1.5,<1.6"
  - DJANGO=django==1.5
install:
  - pip install $DJANGO_PACKAGE --use-mirrors
  - make travis
script: make test
notifications:
  irc: "irc.freenode.org#opps"
  on_success: "never"
